version: '3.8'

services:
  
  flask-app:
    build:
      context: ./app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "${MONGO_URI}"
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static/:/usr/share/nginx/html:ro
    networks:
      - frontend
    depends_on:
      - flask-app


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
