version: '3.8'

services:
  
  flask-app:
    build:
      context: ./app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://root:passwrd@mongo:27017/blog?authSource=admin"
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwrd
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - backend
  
  nginx:
    build:
      context: .
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - flask-app


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
