version: '3.8'

services:
  flask-app:
    build:
      context: ./app
    # command: sh -c "sleep 10s ; python3 main.py"
    # ports:
    #   - "5000:5000"
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    environment:
      MONGO_URI: "mongodb://root:passwrd@mongo:27017/blog?authSource=admin"
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwrd
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.stats()"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./app/blog_post.json:/docker-entrypoint-initdb.d/blog_post.json
    networks:
        - backend
  
  nginx:
    build:
      context: .
    ports:
      - "80:80"
    networks:
     - frontend


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
    # external: true ???
